/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as AuthImport } from './routes/_auth'
import { Route as IndexImport } from './routes/index'
import { Route as authLoginImport } from './routes/(auth)/login'
import { Route as AuthBackstageIndexImport } from './routes/_auth.backstage/index'
import { Route as VoterVoteIdVotingImport } from './routes/voter/$voteId.voting'
import { Route as VoterVoteIdResultImport } from './routes/voter/$voteId.result'
import { Route as VoterVoteIdLoginImport } from './routes/voter/$voteId.login'
import { Route as AuthBackstageVoteCreateImport } from './routes/_auth.backstage/vote/create'
import { Route as AuthBackstageVoteVoteIdIndexImport } from './routes/_auth.backstage/vote/$voteId.index'
import { Route as AuthBackstageQuestionVoteIdIndexImport } from './routes/_auth.backstage/question/$voteId.index'
import { Route as AuthBackstagePasswordVoteIdIndexImport } from './routes/_auth.backstage/password/$voteId.index'
import { Route as AuthBackstageCandidateVoteIdIndexImport } from './routes/_auth.backstage/candidate/$voteId.index'
import { Route as AuthBackstageVoteVoteIdUpdateImport } from './routes/_auth.backstage/vote/$voteId.update'
import { Route as AuthBackstageQuestionVoteIdCreateImport } from './routes/_auth.backstage/question/$voteId.create'
import { Route as AuthBackstageCandidateVoteIdCreateImport } from './routes/_auth.backstage/candidate/$voteId.create'

// Create/Update Routes

const AuthRoute = AuthImport.update({
  id: '/_auth',
  getParentRoute: () => rootRoute,
} as any)

const IndexRoute = IndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRoute,
} as any)

const authLoginRoute = authLoginImport.update({
  id: '/(auth)/login',
  path: '/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthBackstageIndexRoute = AuthBackstageIndexImport.update({
  id: '/backstage/',
  path: '/backstage/',
  getParentRoute: () => AuthRoute,
} as any)

const VoterVoteIdVotingRoute = VoterVoteIdVotingImport.update({
  id: '/voter/$voteId/voting',
  path: '/voter/$voteId/voting',
  getParentRoute: () => rootRoute,
} as any)

const VoterVoteIdResultRoute = VoterVoteIdResultImport.update({
  id: '/voter/$voteId/result',
  path: '/voter/$voteId/result',
  getParentRoute: () => rootRoute,
} as any)

const VoterVoteIdLoginRoute = VoterVoteIdLoginImport.update({
  id: '/voter/$voteId/login',
  path: '/voter/$voteId/login',
  getParentRoute: () => rootRoute,
} as any)

const AuthBackstageVoteCreateRoute = AuthBackstageVoteCreateImport.update({
  id: '/backstage/vote/create',
  path: '/backstage/vote/create',
  getParentRoute: () => AuthRoute,
} as any)

const AuthBackstageVoteVoteIdIndexRoute =
  AuthBackstageVoteVoteIdIndexImport.update({
    id: '/backstage/vote/$voteId/',
    path: '/backstage/vote/$voteId/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthBackstageQuestionVoteIdIndexRoute =
  AuthBackstageQuestionVoteIdIndexImport.update({
    id: '/backstage/question/$voteId/',
    path: '/backstage/question/$voteId/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthBackstagePasswordVoteIdIndexRoute =
  AuthBackstagePasswordVoteIdIndexImport.update({
    id: '/backstage/password/$voteId/',
    path: '/backstage/password/$voteId/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthBackstageCandidateVoteIdIndexRoute =
  AuthBackstageCandidateVoteIdIndexImport.update({
    id: '/backstage/candidate/$voteId/',
    path: '/backstage/candidate/$voteId/',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthBackstageVoteVoteIdUpdateRoute =
  AuthBackstageVoteVoteIdUpdateImport.update({
    id: '/backstage/vote/$voteId/update',
    path: '/backstage/vote/$voteId/update',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthBackstageQuestionVoteIdCreateRoute =
  AuthBackstageQuestionVoteIdCreateImport.update({
    id: '/backstage/question/$voteId/create',
    path: '/backstage/question/$voteId/create',
    getParentRoute: () => AuthRoute,
  } as any)

const AuthBackstageCandidateVoteIdCreateRoute =
  AuthBackstageCandidateVoteIdCreateImport.update({
    id: '/backstage/candidate/$voteId/create',
    path: '/backstage/candidate/$voteId/create',
    getParentRoute: () => AuthRoute,
  } as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexImport
      parentRoute: typeof rootRoute
    }
    '/_auth': {
      id: '/_auth'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof AuthImport
      parentRoute: typeof rootRoute
    }
    '/(auth)/login': {
      id: '/(auth)/login'
      path: '/login'
      fullPath: '/login'
      preLoaderRoute: typeof authLoginImport
      parentRoute: typeof rootRoute
    }
    '/voter/$voteId/login': {
      id: '/voter/$voteId/login'
      path: '/voter/$voteId/login'
      fullPath: '/voter/$voteId/login'
      preLoaderRoute: typeof VoterVoteIdLoginImport
      parentRoute: typeof rootRoute
    }
    '/voter/$voteId/result': {
      id: '/voter/$voteId/result'
      path: '/voter/$voteId/result'
      fullPath: '/voter/$voteId/result'
      preLoaderRoute: typeof VoterVoteIdResultImport
      parentRoute: typeof rootRoute
    }
    '/voter/$voteId/voting': {
      id: '/voter/$voteId/voting'
      path: '/voter/$voteId/voting'
      fullPath: '/voter/$voteId/voting'
      preLoaderRoute: typeof VoterVoteIdVotingImport
      parentRoute: typeof rootRoute
    }
    '/_auth/backstage/': {
      id: '/_auth/backstage/'
      path: '/backstage'
      fullPath: '/backstage'
      preLoaderRoute: typeof AuthBackstageIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/vote/create': {
      id: '/_auth/backstage/vote/create'
      path: '/backstage/vote/create'
      fullPath: '/backstage/vote/create'
      preLoaderRoute: typeof AuthBackstageVoteCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/candidate/$voteId/create': {
      id: '/_auth/backstage/candidate/$voteId/create'
      path: '/backstage/candidate/$voteId/create'
      fullPath: '/backstage/candidate/$voteId/create'
      preLoaderRoute: typeof AuthBackstageCandidateVoteIdCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/question/$voteId/create': {
      id: '/_auth/backstage/question/$voteId/create'
      path: '/backstage/question/$voteId/create'
      fullPath: '/backstage/question/$voteId/create'
      preLoaderRoute: typeof AuthBackstageQuestionVoteIdCreateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/vote/$voteId/update': {
      id: '/_auth/backstage/vote/$voteId/update'
      path: '/backstage/vote/$voteId/update'
      fullPath: '/backstage/vote/$voteId/update'
      preLoaderRoute: typeof AuthBackstageVoteVoteIdUpdateImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/candidate/$voteId/': {
      id: '/_auth/backstage/candidate/$voteId/'
      path: '/backstage/candidate/$voteId'
      fullPath: '/backstage/candidate/$voteId'
      preLoaderRoute: typeof AuthBackstageCandidateVoteIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/password/$voteId/': {
      id: '/_auth/backstage/password/$voteId/'
      path: '/backstage/password/$voteId'
      fullPath: '/backstage/password/$voteId'
      preLoaderRoute: typeof AuthBackstagePasswordVoteIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/question/$voteId/': {
      id: '/_auth/backstage/question/$voteId/'
      path: '/backstage/question/$voteId'
      fullPath: '/backstage/question/$voteId'
      preLoaderRoute: typeof AuthBackstageQuestionVoteIdIndexImport
      parentRoute: typeof AuthImport
    }
    '/_auth/backstage/vote/$voteId/': {
      id: '/_auth/backstage/vote/$voteId/'
      path: '/backstage/vote/$voteId'
      fullPath: '/backstage/vote/$voteId'
      preLoaderRoute: typeof AuthBackstageVoteVoteIdIndexImport
      parentRoute: typeof AuthImport
    }
  }
}

// Create and export the route tree

interface AuthRouteChildren {
  AuthBackstageIndexRoute: typeof AuthBackstageIndexRoute
  AuthBackstageVoteCreateRoute: typeof AuthBackstageVoteCreateRoute
  AuthBackstageCandidateVoteIdCreateRoute: typeof AuthBackstageCandidateVoteIdCreateRoute
  AuthBackstageQuestionVoteIdCreateRoute: typeof AuthBackstageQuestionVoteIdCreateRoute
  AuthBackstageVoteVoteIdUpdateRoute: typeof AuthBackstageVoteVoteIdUpdateRoute
  AuthBackstageCandidateVoteIdIndexRoute: typeof AuthBackstageCandidateVoteIdIndexRoute
  AuthBackstagePasswordVoteIdIndexRoute: typeof AuthBackstagePasswordVoteIdIndexRoute
  AuthBackstageQuestionVoteIdIndexRoute: typeof AuthBackstageQuestionVoteIdIndexRoute
  AuthBackstageVoteVoteIdIndexRoute: typeof AuthBackstageVoteVoteIdIndexRoute
}

const AuthRouteChildren: AuthRouteChildren = {
  AuthBackstageIndexRoute: AuthBackstageIndexRoute,
  AuthBackstageVoteCreateRoute: AuthBackstageVoteCreateRoute,
  AuthBackstageCandidateVoteIdCreateRoute:
    AuthBackstageCandidateVoteIdCreateRoute,
  AuthBackstageQuestionVoteIdCreateRoute:
    AuthBackstageQuestionVoteIdCreateRoute,
  AuthBackstageVoteVoteIdUpdateRoute: AuthBackstageVoteVoteIdUpdateRoute,
  AuthBackstageCandidateVoteIdIndexRoute:
    AuthBackstageCandidateVoteIdIndexRoute,
  AuthBackstagePasswordVoteIdIndexRoute: AuthBackstagePasswordVoteIdIndexRoute,
  AuthBackstageQuestionVoteIdIndexRoute: AuthBackstageQuestionVoteIdIndexRoute,
  AuthBackstageVoteVoteIdIndexRoute: AuthBackstageVoteVoteIdIndexRoute,
}

const AuthRouteWithChildren = AuthRoute._addFileChildren(AuthRouteChildren)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof authLoginRoute
  '/voter/$voteId/login': typeof VoterVoteIdLoginRoute
  '/voter/$voteId/result': typeof VoterVoteIdResultRoute
  '/voter/$voteId/voting': typeof VoterVoteIdVotingRoute
  '/backstage': typeof AuthBackstageIndexRoute
  '/backstage/vote/create': typeof AuthBackstageVoteCreateRoute
  '/backstage/candidate/$voteId/create': typeof AuthBackstageCandidateVoteIdCreateRoute
  '/backstage/question/$voteId/create': typeof AuthBackstageQuestionVoteIdCreateRoute
  '/backstage/vote/$voteId/update': typeof AuthBackstageVoteVoteIdUpdateRoute
  '/backstage/candidate/$voteId': typeof AuthBackstageCandidateVoteIdIndexRoute
  '/backstage/password/$voteId': typeof AuthBackstagePasswordVoteIdIndexRoute
  '/backstage/question/$voteId': typeof AuthBackstageQuestionVoteIdIndexRoute
  '/backstage/vote/$voteId': typeof AuthBackstageVoteVoteIdIndexRoute
}

export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '': typeof AuthRouteWithChildren
  '/login': typeof authLoginRoute
  '/voter/$voteId/login': typeof VoterVoteIdLoginRoute
  '/voter/$voteId/result': typeof VoterVoteIdResultRoute
  '/voter/$voteId/voting': typeof VoterVoteIdVotingRoute
  '/backstage': typeof AuthBackstageIndexRoute
  '/backstage/vote/create': typeof AuthBackstageVoteCreateRoute
  '/backstage/candidate/$voteId/create': typeof AuthBackstageCandidateVoteIdCreateRoute
  '/backstage/question/$voteId/create': typeof AuthBackstageQuestionVoteIdCreateRoute
  '/backstage/vote/$voteId/update': typeof AuthBackstageVoteVoteIdUpdateRoute
  '/backstage/candidate/$voteId': typeof AuthBackstageCandidateVoteIdIndexRoute
  '/backstage/password/$voteId': typeof AuthBackstagePasswordVoteIdIndexRoute
  '/backstage/question/$voteId': typeof AuthBackstageQuestionVoteIdIndexRoute
  '/backstage/vote/$voteId': typeof AuthBackstageVoteVoteIdIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/': typeof IndexRoute
  '/_auth': typeof AuthRouteWithChildren
  '/(auth)/login': typeof authLoginRoute
  '/voter/$voteId/login': typeof VoterVoteIdLoginRoute
  '/voter/$voteId/result': typeof VoterVoteIdResultRoute
  '/voter/$voteId/voting': typeof VoterVoteIdVotingRoute
  '/_auth/backstage/': typeof AuthBackstageIndexRoute
  '/_auth/backstage/vote/create': typeof AuthBackstageVoteCreateRoute
  '/_auth/backstage/candidate/$voteId/create': typeof AuthBackstageCandidateVoteIdCreateRoute
  '/_auth/backstage/question/$voteId/create': typeof AuthBackstageQuestionVoteIdCreateRoute
  '/_auth/backstage/vote/$voteId/update': typeof AuthBackstageVoteVoteIdUpdateRoute
  '/_auth/backstage/candidate/$voteId/': typeof AuthBackstageCandidateVoteIdIndexRoute
  '/_auth/backstage/password/$voteId/': typeof AuthBackstagePasswordVoteIdIndexRoute
  '/_auth/backstage/question/$voteId/': typeof AuthBackstageQuestionVoteIdIndexRoute
  '/_auth/backstage/vote/$voteId/': typeof AuthBackstageVoteVoteIdIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | ''
    | '/login'
    | '/voter/$voteId/login'
    | '/voter/$voteId/result'
    | '/voter/$voteId/voting'
    | '/backstage'
    | '/backstage/vote/create'
    | '/backstage/candidate/$voteId/create'
    | '/backstage/question/$voteId/create'
    | '/backstage/vote/$voteId/update'
    | '/backstage/candidate/$voteId'
    | '/backstage/password/$voteId'
    | '/backstage/question/$voteId'
    | '/backstage/vote/$voteId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | ''
    | '/login'
    | '/voter/$voteId/login'
    | '/voter/$voteId/result'
    | '/voter/$voteId/voting'
    | '/backstage'
    | '/backstage/vote/create'
    | '/backstage/candidate/$voteId/create'
    | '/backstage/question/$voteId/create'
    | '/backstage/vote/$voteId/update'
    | '/backstage/candidate/$voteId'
    | '/backstage/password/$voteId'
    | '/backstage/question/$voteId'
    | '/backstage/vote/$voteId'
  id:
    | '__root__'
    | '/'
    | '/_auth'
    | '/(auth)/login'
    | '/voter/$voteId/login'
    | '/voter/$voteId/result'
    | '/voter/$voteId/voting'
    | '/_auth/backstage/'
    | '/_auth/backstage/vote/create'
    | '/_auth/backstage/candidate/$voteId/create'
    | '/_auth/backstage/question/$voteId/create'
    | '/_auth/backstage/vote/$voteId/update'
    | '/_auth/backstage/candidate/$voteId/'
    | '/_auth/backstage/password/$voteId/'
    | '/_auth/backstage/question/$voteId/'
    | '/_auth/backstage/vote/$voteId/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AuthRoute: typeof AuthRouteWithChildren
  authLoginRoute: typeof authLoginRoute
  VoterVoteIdLoginRoute: typeof VoterVoteIdLoginRoute
  VoterVoteIdResultRoute: typeof VoterVoteIdResultRoute
  VoterVoteIdVotingRoute: typeof VoterVoteIdVotingRoute
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AuthRoute: AuthRouteWithChildren,
  authLoginRoute: authLoginRoute,
  VoterVoteIdLoginRoute: VoterVoteIdLoginRoute,
  VoterVoteIdResultRoute: VoterVoteIdResultRoute,
  VoterVoteIdVotingRoute: VoterVoteIdVotingRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.tsx",
      "children": [
        "/",
        "/_auth",
        "/(auth)/login",
        "/voter/$voteId/login",
        "/voter/$voteId/result",
        "/voter/$voteId/voting"
      ]
    },
    "/": {
      "filePath": "index.tsx"
    },
    "/_auth": {
      "filePath": "_auth.tsx",
      "children": [
        "/_auth/backstage/",
        "/_auth/backstage/vote/create",
        "/_auth/backstage/candidate/$voteId/create",
        "/_auth/backstage/question/$voteId/create",
        "/_auth/backstage/vote/$voteId/update",
        "/_auth/backstage/candidate/$voteId/",
        "/_auth/backstage/password/$voteId/",
        "/_auth/backstage/question/$voteId/",
        "/_auth/backstage/vote/$voteId/"
      ]
    },
    "/(auth)/login": {
      "filePath": "(auth)/login.tsx"
    },
    "/voter/$voteId/login": {
      "filePath": "voter/$voteId.login.tsx"
    },
    "/voter/$voteId/result": {
      "filePath": "voter/$voteId.result.tsx"
    },
    "/voter/$voteId/voting": {
      "filePath": "voter/$voteId.voting.tsx"
    },
    "/_auth/backstage/": {
      "filePath": "_auth.backstage/index.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/vote/create": {
      "filePath": "_auth.backstage/vote/create.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/candidate/$voteId/create": {
      "filePath": "_auth.backstage/candidate/$voteId.create.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/question/$voteId/create": {
      "filePath": "_auth.backstage/question/$voteId.create.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/vote/$voteId/update": {
      "filePath": "_auth.backstage/vote/$voteId.update.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/candidate/$voteId/": {
      "filePath": "_auth.backstage/candidate/$voteId.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/password/$voteId/": {
      "filePath": "_auth.backstage/password/$voteId.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/question/$voteId/": {
      "filePath": "_auth.backstage/question/$voteId.index.tsx",
      "parent": "/_auth"
    },
    "/_auth/backstage/vote/$voteId/": {
      "filePath": "_auth.backstage/vote/$voteId.index.tsx",
      "parent": "/_auth"
    }
  }
}
ROUTE_MANIFEST_END */
